---

flavor: 4c16g30d
registry_node: utilityvm.example.com
install_dir: "{{ lookup('env','INSTALL_DIR') }}"
INFRA_ID: "{{ lookup('env','INFRA_ID') }}"
ocp_image: rhcos-ocp43

domain_name: blue.osp.opentlc.com
cluster_name: cluster-5437
project_name: 5437-project
bootstrap_node: "{{ INFRA_ID }}-bootstrap.example.com"
priv_key: /home/mradecke-redhat.com/.ssh/5437key.pem
ocp_network: 5437-ocp-network
ocp_master_sg: 5437-master_sg
ocp_worker_sg: 5437-worker_sg
ocp_subnet: 5437-ocp-subnet

lb_ip: 169.47.188.136

merged_secret_path: /home/mradecke-redhat.com/merged_pullsecret.json
ocp_pull_secret: /home/mradecke-redhat.com/ocp_pullsecret.json
registry_pull_secret: /home/mradecke-redhat.com/pullsecret_config.json
