---

flavor: 4c16g30d
registry_node: utilityvm.example.com
install_dir: "{{ lookup('env','INSTALL_DIR') }}"
INFRA_ID: "{{ lookup('env','INFRA_ID') }}"
ocp_image: rhcos-ocp43

domain_name: blue.osp.opentlc.com
cluster_name: cluster-$GUID
project_name: $GUID-project
bootstrap_node: "{{ INFRA_ID }}-bootstrap.example.com"
priv_key: /home/mradecke-redhat.com/.ssh/$GUIDkey.pem
ocp_network: $GUID-ocp-network
ocp_master_sg: $GUID-master_sg
ocp_worker_sg: $GUID-worker_sg
ocp_subnet: $GUID-ocp-subnet

lb_ip: 169.47.188.136

merged_secret_path: /home/mradecke-redhat.com/merged_pullsecret.json
ocp_pull_secret: /home/mradecke-redhat.com/ocp_pullsecret.json
registry_pull_secret: /home/mradecke-redhat.com/pullsecret_config.json
