---

LOCAL_REGISTRY: utilityvm.example.com:5000
LOCAL_REPOSITORY: ocp4/openshift4
LOCAL_SECRET_JSON: '{{ merged_secret_path }}'
PRODUCT_REPO: openshift-release-dev
RELEASE_NAME: ocp-release
OCP_RELEASE: 4.3.13-x86_64


user: openshift
user_passwd: redhat
registry_dir: /opt/registry
registry_name: utilityvm.example.com
home_dir: /home/mradecke-redhat.com
merged_secret_path: /home/mradecke-redhat.com/merged_pullsecret.json
ocp_pull_secret: /home/mradecke-redhat.com/ocp_pullsecret.json
registry_pull_secret: /home/mradecke-redhat.com/pullsecret_config.json


install_dir: "{{ lookup('env','INSTALL_DIR') }}"
owner: mradecke-redhat.com
