---

- name: Create environment variables
  blockinfile:
    path: '{{ home_dir }}/.bashrc'
    block: |
      export LOCAL_REGISTRY=utilityvm.example.com:5000
      export LOCAL_REPOSITORY=ocp4/openshift4
      export LOCAL_SECRET_JSON='{{ install_dir }}/merged_pullsecret.json'
      export PRODUCT_REPO=openshift-release-dev
      export RELEASE_NAME=ocp-release
      export OCP_RELEASE=4.3.13
      export INSTALL_DIR=$HOME/openstack-upi

- name: Source .bashrc
  shell: 'source {{ home_dir }}/.bashrc'

- name: Create installation directory with backup and ssl
  file:
    path: "{{ install_dir }}/{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ owner }}"
  loop:
  - bak
  - ssl
  - data
  - mirror
  - auth
  - registry
  - user-data
  - .ssh

- name: Download OpenShift CLI
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ OCP_RELEASE }}/openshift-client-linux-{{ OCP_RELEASE }}.tar.gz
    dest: "{{ install_dir }}" 

- name: Extract OC client 
  unarchive:
    src: '{{ install_dir }}/openshift-client-linux-{{ OCP_RELEASE }}.tar.gz'
    dest: '{{ install_dir }}'

- name: Copy the kubectl and oc commands to PATH
  copy:
    src: '{{ install_dir }}/{{ item }}'
    dest: /usr/local/sbin
    mode: 0755
  loop:
  - oc
  - kubectl

- name: Set up bash completion for OC client
  shell: '/usr/local/bin/oc completion bash | sudo tee /etc/bash_completion.d/openshift > /dev/null'

- name: Download openshift-install binary
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux.tar.gz
    dest: "{{ install_dir }}"

- name: Extract openshift-install
  unarchive:
    src: '{{ install_dir }}/openshift-install-linux.tar.gz'
    dest: '{{ install_dir }}'

- name: Copy the openshift-install to PATH
  copy:
    src: '{{ install_dir }}/openshift-install'
    dest: /usr/local/sbin
    mode: 0755

- name: Generate ssh keys for core user
  openssh_keypair:
    path: '{{ install_dir }}/.ssh/id_rsa'
    comment: 'core@{{ domain_name }}'  
    state: present
    force: no
