---

- name: Create environment variables
  blockinfile:
    path: '{{ home_dir }}/.bashrc'
    block: |
      export LOCAL_REGISTRY=utilityvm.example.com:5000
      export LOCAL_REPOSITORY=ocp4/openshift4
      export LOCAL_SECRET_JSON=/home/$USER/merged_pullsecret.json
      export PRODUCT_REPO=openshift-release-dev
      export RELEASE_NAME=ocp-release
      export OCP_RELEASE=4.3.13

- name: Source .bashrc
  shell: source {{ home_dir }}/.bashrc

- name: Download OpenShift CLI
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ OCP_RELEASE }}/openshift-client-linux-{{ OCP_RELEASE }}.tar.gz
    dest: "{{ home_dir }}" 

- name: Extract OC client and move to PATH
  unarchive:
    src: '{{ home_dir }}/openshift-client-linux-{{ OCP_RELEASE }}.tar.gz'
    dest: /usr/local/sbin/

- name: Set up bash completion for OC client
  shell: oc completion bash | sudo tee /etc/bash_completion.d/openshift > /dev/null

